# storage.py
# ------
from typing import Iterable, Optional, Dict, Any, List, Tuple

Recipe = Dict[str, Any]        # title, steps(list[str]), tags(list[str]), ingredients(dict[str,str]), servings?, source_url?
GroceryLine = Tuple[str, str]  # (ingredient_name, amount)

class Storage:
    """Abstract recipe storage."""

    # Basic CRUD
    def list_recipes(self) -> List[Recipe]: ...
    def get_recipe(self, title: str) -> Optional[Recipe]: ...
    def add_recipe(self, recipe: Recipe) -> None: ...
    def delete_recipe(self, title: str) -> bool: ...
    def save(self) -> None: ...

    # Convenience
    def random_recipes(self, n: int = 1, tag: Optional[str] = None) -> List[Recipe]: ...
    def grocery_list(self, recipes: List[Recipe]) -> List[GroceryLine]: ...

    # Bulk helpers
    def import_iter(self, recipes: Iterable[Recipe]) -> int: ...
    def export_iter(self) -> Iterable[Recipe]: ...
